### ISSUE TITLE
can't compile on Ubuntu 20.04 with gcc 9.3.0

### ISSUE THREAD

**Issue by derhuerst** [blechschmidt/freebind#3]
I'm not very experienced with the C language & toolchain, so I failed to solve this on my own.

```shell
uname -a
# Linux testing-2 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
gcc --version
# gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

```shell
apt install -y gcc make git
git clone https://github.com/blechschmidt/freebind.git
cd freebind
make
```

```
mkdir -p bin
gcc -Wall -shared -fPIC src/freebind.c -o bin/freebind.so -ldl
gcc -Wall src/preloader.c -o bin/freebind
src/preloader.c: In function ‘main’:
src/preloader.c:46:6: error: a label can only be part of a statement and a declaration is not a statement
   46 |      size_t buflen = strlen(buf);
      |      ^~~~~~
make: *** [Makefile:6: default] Error 1
```

**Comment by blechschmidt** [comment]
This has been fixed by c17792736713547dd9e03e8cc20c9ddcac90adaa.
